sonar.projectKey=myproject
sonar.projectName=localizationtest
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=target/classes
sonar.host.url=http://localhost:9000
sonar.login=squ_c5a4d39dd38ba157bca742bfdfea4a8aae3aef7c