sonar.projectKey=safetynet
sonar.projectName=safetynet
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=target/classes
sonar.host.url=http://localhost:9000
sonar.token=squ_7f8eeeb7472fe1bfa00ec1221a1a59abb14d608c
sonar.scanner.tempPath=C:\Users\jerep\JavaProjects